prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 6

prometheusOperator:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 6

alertmanager:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 6

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 6

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
